### ISSUE TITLE
Submit the assignment 4

### ISSUE THREAD

**Issue by lazybee27102** [lazybee27102/BeeTwitterUltimate#1]
Here is my completed homework assignment.Please review it and send me your feedback.Thank you!!!! I will upload video walkthrough in a few minutes
/cc @coderschoolreview @hoanle

**Comment by hoanle** [comment]
:+1: Great work. A few notes after checking out the code:
- It's definitely the most complicated submission till now. It has everything an app needs to be commercial: nice UI, fantastic animation, various features...
- Nice to see you used a drawable and/or styles to customize the view
- For the sliding tabs, [try styling the tabs](https://guides.codepath.com/android/Sliding-Tabs-with-PagerSlidingTabStrip#customize-tab-styles) to customize their appearance.
- Nice to see you have progress bars displayed during background tasks
- Correctly and appropriately used OnClickListeners on the user's profile image to navigate to their profile view
- Good to see you properly communicated the user to the user timeline fragment from the profile activity.
- Glad to see you properly hooked up each of the different timelines to infinitely paginate.
- For a future exercise, challenge yourself to move even more of the logic into the base Fragment class and out of the extension timeline fragments. For example, the scroll listener could be set in the base class and then the "onLoadMore" could call an abstract method which is defined separately in the extended class. This approach could be used to move almost all the logic into the base except for certain key abstract methods.
- There are a few crashes, but they can be fixed easily. For example

```
 java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                        at java.util.ArrayList.get(ArrayList.java:308)
                                                                                        at com.codepath.apps.beetwitterultimate.Tab.MentionTabFragment$3.onSuccess(MentionTabFragment.java:123)


                                                                                         Process: com.codepath.apps.restclienttemplate, PID: 2537
                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                        at com.codepath.apps.beetwitterultimate.MainActivity.Profile.ProfileActivity$1.onSuccess(ProfileActivity.java:94)
```
- The app still has a lot of duplicate code. For example, although you have reused the MentionAdapter, the code inside where user clicks to share, reweet... can be found in TweetAdapter. 
My suggestion: 
- Create a base adapter without duplicate code, extend it to use later
- Create a custom view for the tweet bar (the bar with various actions). Integrate actions into it and use it as a view in layout. Save a lot of code
- You also need to organise the code, classes, package. Your current style of packaging makes sense for yourself and for this project (small one, not many modules). But when the project gets bigger, more module coming, this style will be a nightmare. You also need to name variable with a meaningful name so that other developer could understand its role. For example this variable makes no sense at all
`String a = b.getString(GlobalVariable.CURRENT_FROM_TWEET_TO_PROFILE);` 


Here's a detailed [Project 4 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_4_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission.

This week (Week 5), we are going to cover the last major piece to the Android puzzle and that is using the hardware and SDK components such as the camera, photo gallery, location, maps, etc. After that, Week 6 and week 7 we will be covering a few important intermediate topics such as more about styling and animation as well as testing.

Following the bootcamp, we are going to have a public demo day to celebrate the progress you've all made with our next batch of Android students and multiple companies attending to see the group projects that you all have built. We are going to help however we can over the next few weeks to get the team project apps in shape for that.
